export const muscleList: string[] = [
  "Abdominals",
  "Hamstrings",
  "Adductors",
  "Quadriceps",
  "Biceps",
  "Shoulders",
  "Chest",
  "Middle Back",
  "Calves",
  "Glutes",
  "Lower Back",
  "Lats",
  "Triceps",
  "Traps",
  "Forearms",
  "Neck",
  "Abductors",
];